* Selenium WebDriver tests for AmiGO 2
  This is still in progress, but we have a start.

  You should hopefully be a little familiar with the Selenium
  [[https://code.google.com/p/selenium/wiki/WebDriverJs][WebDriveJS]] documentation.

  In addition, we'll be using the [[http://mochajs.org][Mocha]] testing framework and the [[http://chaijs.com/][Chai]]
  assertion library.

** Getting Started

   First, if you do not already have it, you will need a recent
   version of [[http://nodejs.org/download/][Node.js]]. As of the writing at this moment, I'm
   developing on v0.10.36.

   Next, after checking out the GitHub [[https://github.com/geneontology/amigo][geneontology/amigo]] repository,
   move into the Selenium WebDriver test directory.

   : cd amigo/selenium/webdriver   

   A well commented primer on the basics of testing with can be found
   in [[test_examples.js][test_examples.js]]. I'd suggest reading that before digging into
   the unit test files proper. Read all the way through as there are
   negative examples as well.

   To run these examples, try:

   : AMIGO=http://amigo.geneontology.org node test_examples.js

   These examples can be run headless as well.

** CLI Usage (TODO)

   To run all the tests:

   : AMIGO=http://amigo.geneontology.org ./node_modules/mocha/bin/mocha -g *_tests.js

   Or just choose the location of AmiGO that you want to run
   against:

   : AMIGO=http://amigo.geneontology.org node core_tests.js

** Headless Usage (TODO)
   Naturally, we'll require:

   * xvfb
   * firefox
   * node (use their repo to get a decent one)

   Running could be like:

   : Xvfb :1 -screen 5 1024x768x8
   : DISPLAY=:1.5 AMIGO=http://amigo.geneontology.org node test.js
