####
#### The annotation description file for GOlr and AmiGO.
####
id: annotation
schema_generating: true
description: Associations between GO terms and genes or gene products.
display_name: Annotations
document_category: annotation
weight: 20
boost_weights: annotation_class^2.0 annotation_class_label^1.0 bioentity^2.0 bioentity_label^1.0 bioentity_name^1.0 annotation_extension_class^2.0 annotation_extension_class_label^1.0 reference^1.0 panther_family^1.0 panther_family_label^1.0 bioentity_isoform^1.0 regulates_closure^1.0 regulates_closure_label^1.0
result_weights: bioentity^7.0 bioentity_name^6.0 qualifier^5.0 annotation_class^4.7 annotation_extension_json^4.5 assigned_by^4.0 taxon^3.0 evidence_type^2.5 evidence_with^2.0 panther_family^1.5 type^1.0 bioentity_isoform^0.5 reference^0.25 date^0.10
filter_weights: aspect^10.0 taxon_subset_closure_label^9.0 type^8.5 evidence_subset_closure_label^8.0 regulates_closure_label^7.0 annotation_class_label^6.0 qualifier^5.0 annotation_extension_class_closure_label^4.0 assigned_by^3.0 panther_family_label^2.0
fields:
  - id: id
    description: A unique (and internal) combination of bioentity and ontology class.
    display_name: Acc
    type: string
    property: []
  - id: source
    description: "Database source."
    display_name: Source
    type: string
    property: []
  - id: type
    description: "Type class."
    display_name: Type
    type: string
    property: []
#   - id: type_label
#     description: "GAF column 12 (type class label)"
#     display_name: Type class label
#     type: string
#     property: []
  - id: date
    description: "Date of assignment."
    display_name: Date
    type: string
    property: []
  - id: assigned_by
    description: "Annotations assigned by group."
    display_name: Contributor
    type: string
    property: []
  - id: is_redundant_for
    description: "Rational for redundancy of annotation."
    display_name: Redundant for
    type: string
    property: []
#   - id: type_closure
#     description: "Derived from c12 + SO."
#     display_name: Type closure
#     type: string
#     cardinality: multi
#     property: []
#   - id: type_closure_label
#     description: "Derived from c12 + SO."
#     display_name: Type label closure
#     type: string
#     cardinality: multi
#     property: []
  - id: taxon
    description: "Taxonomic group."
    display_name: Organism
    type: string
    property: []
  - id: taxon_label
    description: "Taxonomic group and ancestral groups."
    display_name: Organism
    type: string
    property: []
    searchable: true
  - id: taxon_closure
    description: "Taxonomic group and ancestral groups."
    display_name: Organism
    type: string
    cardinality: multi
    property: []
  - id: taxon_closure_label
    description: "Taxonomic group and ancestral groups."
    display_name: Organism
    type: string
    cardinality: multi
    property: []
    searchable: true
  - id: taxon_subset_closure
    description: "Taxonomic group (direct) and ancestral groups that are within the specified subset (e.g mammalia, eukaryota)."
    display_name: Organism
    type: string
    cardinality: multi
    property: []
  - id: taxon_subset_closure_label
    description: "Taxonomic group (direct) and ancestral groups that are within the specified subset (e.g mammalia, eukaryota)."
    display_name: Organism
    type: string
    cardinality: multi
    property: []
    searchable: true
  - id: secondary_taxon
    description: "Secondary taxon."
    display_name: Secondary taxon
    type: string
    property: []
  - id: secondary_taxon_label
    description: "Secondary taxon."
    display_name: Secondary taxon
    type: string
    property: []
    searchable: true
  - id: secondary_taxon_closure
    description: "Secondary taxon closure."
    display_name: Secondary taxon
    type: string
    cardinality: multi
    property: []
  - id: secondary_taxon_closure_label
    description: "Secondary taxon closure."
    display_name: Secondary taxon
    type: string
    cardinality: multi
    property: []
    searchable: true
  - id: isa_partof_closure
    description: "Annotations for this term or its children (over is_a/part_of). When used to query bioentities, this corresponds to 'involved in' in RO"
    display_name: Involved in
    type: string
    cardinality: multi
    property: []
  - id: isa_partof_closure_label
    description: "Annotations for this term or its children (over is_a/part_of)."
    display_name: Involved in
    type: string
    cardinality: multi
    property: []
    searchable: true
  - id: regulates_closure
    description: "Annotations for this term or its children (over regulates, including isa/part-of). Note the field name is potentially confusing, as it includes cases where there are no actual regulates edges. When used to query bioentities, this corresponds to 'acts upstream of or within'"
    display_name: GO class
    type: string
    cardinality: multi
    property: []
  - id: regulates_closure_label
    description: "Annotations for this term or its children (over regulates, including isa/part-of)."
    display_name: GO class
    type: string
    cardinality: multi
    property: []
    searchable: true
  - id: regulates_strict_closure
    description: "Annotations for this term or its children (over regulates, but not part-of). When used to query bioentities, this corresponds to 'involved in regulation of'"
    display_name: GO class
    type: string
    cardinality: multi
    property: []
  - id: regulates_strict_closure_label
    description: "Annotations for this term or its children (over regulates, but not part-of)."
    display_name: GO class
    type: string
    cardinality: multi
    property: []
    searchable: true
  - id: has_participant_closure
    description: "Closure of ids/accs over has_participant."
    display_name: Has participant (IDs)
    type: string
    cardinality: multi
    property: []
  - id: has_participant_closure_label
    description: "Closure of labels over has_participant."
    display_name: Has participant
    type: string
    cardinality: multi
    property: []
    searchable: true
#   - id: label
#     description: Symbol or name.
#     display_name: Label
#     type: string
#     property: []
#     searchable: true
#   - id: descriptive_name
#     description: Full name or name.
#     display_name: Full name
#     type: string
#     property: []
#     searchable: true
  - id: synonym
    description: "Gene or gene product synonyms."
    display_name: Synonym
    type: string
    cardinality: multi
    property: []
    searchable: true
#   - id: alternate_id
#     description: Any alternaitve id.
#     display_name: Alt id
#     type: string
#     cardinality: multi
#     property: []
#   - id: description
#     description: Definition.
#     display_name: Definition
#     type: string
#     property: []
#     searchable: true
#   - id: subset
#     description: Member of these named subsets.
#     display_name: Subset
#     type: string
#     cardinality: multi
#     property: []
#   - id: is_obsolete
#     description: Is this obsolete?
#     display_name: Obsolete
#     type: integer
#     property: []
#   - id: comment
#     description: Comment.
#     display_name: comment
#     type: string
# #    cardinality: multi
#     property: []
#     searchable: true
#   - id: definition_xref
#     description: DBXref for definitions.
#     display_name: Def dbxref
#     type: string
#     cardinality: multi
#     property: []
#   - id: annotation_closure
#     description: All terms associatied with GP.
#     display_name: All annotations
#     type: string
#     cardinality: multi
#     property: []
  - id: bioentity
    description: "Gene or gene product identifiers."
    display_name: Gene/product
    type: string
    property: []
  - id: bioentity_label
    description: "Gene or gene product identifiers."
    display_name: Gene/product
    type: string
    property: []
    searchable: true
  - id: bioentity_name
    description: "The full name of the gene or gene product."
    display_name: Gene/product name
    type: string
    property: []
    searchable: true
  - id: bioentity_internal_id
    description: "The bioentity ID used at the database of origin."
    display_name: This should not be displayed
    type: string
    property: []
    indexed: false
#   - id: bioentity_alternate_label
#     description: Alternate label.
#     display_name: Alternate label
#     type: string
#     cardinality: multi
#     property: []
#   - id: is_negated
#     description: Derived from column 4.
#     display_name: Is not
#     type: string
#     property: []
  - id: qualifier
    description: "Annotation qualifier."
    display_name: Annotation qualifier
    type: string
    cardinality: multi
    property: []
  - id: annotation_class
    description: "Direct annotations."
    display_name: GO class (direct)
    type: string
    property: []
  - id: annotation_class_label
    description: "Direct annotations."
    display_name: GO class (direct)
    type: string
    property: []
    searchable: true
  - id: aspect
    description: "Ontology aspect."
    display_name: Ontology (aspect)
    type: string
    property: []
  - id: bioentity_isoform
    description: "Biological isoform."
    display_name: Isoform
    type: string
    property: []
#   - id: bioentity_isoform_label
#     description: ???
#     display_name: Bioentity isoform label
#     type: string
#     cardinality: multi
#     property: []
  - id: evidence_type
    description: "Evidence type. (legacy)"
    display_name: Evidence
    type: string
    property: []
  - id: evidence_type_closure
    description: "All evidence (evidence closure) for this annotation. (legacy)"
    display_name: Evidence type
    type: string
    cardinality: multi
    property: []
  - id: evidence_with
    description: "Evidence with/from."
    display_name: Evidence with
    type: string
    searchable: true
    cardinality: multi
    property: []
  - id: evidence
    description: "Evidence."
    display_name: Evidence
    type: string
    property: []
  - id: evidence_label
    description: "Evidence."
    display_name: Evidence
    type: string
    property: []
    searchable: true
  - id: evidence_closure
    description: "All evidence for this annotation."
    display_name: Evidence
    type: string
    cardinality: multi
    property: []
  - id: evidence_closure_label
    description: "All evidence for this annotation."
    display_name: Evidence
    type: string
    cardinality: multi
    property: []
    searchable: true
  - id: evidence_subset_closure
    description: "All evidence for this annotation reduced to a usable subset."
    display_name: Evidence
    type: string
    cardinality: multi
    property: []
  - id: evidence_subset_closure_label
    description: "All evidence for this annotation reduced to a usable subset."
    display_name: Evidence
    type: string
    cardinality: multi
    property: []
    searchable: true
  - id: reference
    description: "Database reference."
    display_name: Reference
    type: string
    cardinality: multi
    ## Added for compat purposes with model-ann.yaml
    searchable: true
    property: []
  - id: annotation_extension_class
    description: "Extension class for the annotation."
    display_name: Annotation extension
    type: string
    cardinality: multi
    property: []
  - id: annotation_extension_class_label
    description: "Extension class for the annotation."
    display_name: Annotation extension
    type: string
    cardinality: multi
    property: []
    searchable: true
  - id: annotation_extension_class_closure
    description: "Extension class for the annotation."
    display_name: Annotation extension
    type: string
    cardinality: multi
    property: []
  - id: annotation_extension_class_closure_label
    description: "Extension class for the annotation."
    display_name: Annotation extension
    type: string
    cardinality: multi
    property: []
    searchable: true
  - id: annotation_extension_json
    description: "Extension class for the annotation (JSON)."
    display_name: Annotation extension
    type: string
    cardinality: multi
    property: []
  - id: panther_family
    description: PANTHER families that are associated with this entity.
    display_name: PANTHER family
    type: string
    searchable: true
    property: []
  - id: panther_family_label
    description: PANTHER families that are associated with this entity.
    display_name: PANTHER family
    type: string
    searchable: true
    property: []
## Experimental fields.
  - id: geospatial_x
    description: Experimental numeric type (X).
    display_name: X
    type: integer
    searchable: false
    indexed: true
    cardinality: multi
    property: []
  - id: geospatial_y
    description: Experimental numeric type (Y).
    display_name: Y
    type: integer
    searchable: false
    indexed: true
    cardinality: multi
    property: []
  - id: geospatial_z
    description: Experimental numeric type (Z).
    display_name: Z
    type: integer
    searchable: false
    indexed: true
    cardinality: multi
    property: []
  ## TODO:
  # - id: phylo_graph
  #   description: JSON blob form of the phylogenic tree.
  #   display_name: This should not be displayed
  #   type: string
  #   property: []
  #   indexed: false
  ## TODO: Sleeping for now, but will re-add when the right
  ## experimental GAFs start getting loaded as well.
  # - id: phylo_ancestor_closure
  #   description: All ancestors of this entity.
  #   display_name: Phylogenic ancestors
  #   type: string
  #   cardinality: multi
  #   property: []
  # - id: phylo_descendant_closure
  #   description: All descendants of this entity.
  #   display_name: Phylogenic descendants
  #   type: string
  #   cardinality: multi
  #   property: []
